### ISSUE TITLE
Cannot find module 'eslint-config-prettier/react'

### ISSUE THREAD

**Issue by oscar-b** [lydell/eslint-config-prettier#2]
eslint gives me the error: `Cannot find module 'eslint-config-prettier/react'` with the following config, anything I'm doing wrong?

```
{
    "extends": [
      "eslint:recommended",
      "plugin:react/recommended",
      "prettier",
      "prettier/react"
    ],
    "parser": "babel-eslint",
    "plugins": [
        "react",
        "prettier"
    ],
    "parserOptions": {
      "ecmaVersion": 2016,
      "sourceType": "module",
      "ecmaFeatures": {
        "jsx": true
      }
    },
    "env": {
      "es6": true,
      "node": true
    },
    "globals": {
        "localStorage": true,
        "ga": true,
        "fetch": true,
        "window": true,
        "document": true,
        "Raven": true,
        "ENV": true
    },
    "rules": {
        "prettier/prettier": ["error", {"trailingComma": true, "singleQuote": true}],
        "no-console": 0,
        "react/sort-comp": [1, {
            "order": [
                "type-annotations",
                "static-methods",
                "lifecycle",
                "everything-else",
                "render"
            ]
        }]
    }
}
```

**Comment by lydell** [comment]
You are correct, I'm wrong. Sorry! I've published 1.0.3 – it should work.

**Comment by oscar-b** [comment]
Thanks, seems better now! :)

**Comment by f00z** [comment]
can you share what was causing it? I am getting same error and I dont know what is causing it

**Comment by lydell** [comment]
@f00z [Some files where accidentally not included in the npm package](https://github.com/prettier/eslint-config-prettier/commit/fbe20e306f87c15296c1c17bfeed62485ebb06f7#diff-b9cfc7f2cdf78a7f4b91a753d10865a2L10).

**Comment by f00z** [comment]
I had to use local eslint to fix the issue. https://github.com/btholt/complete-intro-to-react/issues/66

**Comment by Ciwan1859** [comment]
@lydell I'm still having [the same issue](https://stackoverflow.com/q/44824216/613605).

**Comment by lydell** [comment]
@Ciwan1859 You seem to get the same error _message,_ but for a completely different reason than this issue was about.

**Comment by theskillwithin** [comment]
I seem to be experiencing this now

**Comment by SimpleCookie** [comment]
@theskillwithin Me too

**Comment by Simbaxo** [comment]
does anyone know how to get this to work when eslint is installed globally?

**Comment by Deelux** [comment]
I am still getting this error. Anyone have a fix??

**Comment by lydell** [comment]
@Deelux Yes! Upgrade to the latest version and [learn about ESLint plugins](https://eslint.org/docs/user-guide/configuring#configuring-plugins):

> **Note:** Due to the behavior of Node’s `require` function, a globally-installed instance of ESLint can only use globally-installed ESLint plugins, and locally-installed version can only use _locally-installed_ plugins. Mixing local and global plugins is not supported.

**Comment by mdarif** [comment]
+1, getting the same.

**Comment by kingluddite** [comment]
npm i eslint-config-prettier@latest

**Comment by marcospgp** [comment]
I get this but regarding `Cannot find module 'eslint-config-prettier/@typescript-eslint'`

**Comment by hussainakram** [comment]
`yarn add --dev eslint-config-prettier `

**Comment by lcampanari** [comment]
I experienced the same problem today. Here is how it happened: 

1. Things were working correctly
1. I disabled "eslint.validate" for javascript on my vscode's settings so I could test something
1. I installed another dependency on my project
1. I enabled  "eslint.validate" for javascript
1. The error started

I followed @hussainakram's comment and things got back to normal. 

If that doesn't work I guess you could try to remove your package-lock.json and `npm install` again.

**Comment by lydell** [comment]
In [version 8.0.0](https://github.com/prettier/eslint-config-prettier/blob/0dd2a7ed26f5ce2cd35ff242228afaaf2fe2de2b/CHANGELOG.md#version-800-2021-02-21), all configs have been merged into one. So `"prettier/react"` does not exist anymore.

The solution is to:

1. Update to eslint-config-prettier 8.0.0 or later.

2. Remove any `"prettier/*"` from `"extends"`:

  ```json
  {
    "extends": [
      "some-other-config-you-use",
      "prettier",
      "prettier/react"
    ]
  }
  ```

  ⬇️ 

  ```json
  {
    "extends": [
      "some-other-config-you-use",
      "prettier"
    ]
  }
  ```

**Comment by Rajek88** [comment]
This worked, Thank you so much
